### ISSUE TITLE
Add a copy of the MIT license to the repository

### ISSUE THREAD

**Issue by Calinou** [thiagobruno/godot_analogcontroller#1]
The asset submission says the asset's license is MIT. Please add a copy of the MIT license to the repository to confirm this :slightly_smiling_face:

**Comment by thrbr84** [comment]
I uploaded the MIT LICENSE file, thanks.

**Comment by Calinou** [comment]
Thanks! The asset is now approved: https://godotengine.org/asset-library/asset/572
