### ISSUE TITLE
Mobile Device Multi-touch Question

### ISSUE THREAD

**Issue by rseonp** [thiagobruno/godot_analogcontroller#3]
Hi Thiago,

First, thanks for this amazing add-on and documentation. 

I'm having trouble getting the analog to function a certain way on a mobile device. I'm able to use the analog on its own, as well as simultaneously holding/moving while clicking a touch screen button IF I use the analog stick first. However, if I click and hold down anywhere prior to using the analog, the analog doesn't appear to register any input. 

Do you have any advice on where to look inside analog.gd (or somewhere else) to potentially resolve this issue? 

Thanks!

**Comment by rseonp** [comment]
I figured it out!

The problem was that Godot registers the initial touch event as an InputEventMouseButton, but any touches after that get registered as InputEventScreenTouch events (similarly for MouseMotion and ScreenDrag). 

The changes I made: 

- inside process_input, I appended Touch and Drag events to the if check preceding the calculateForce(...) line
- instead of checking for MouseMotion I check for ScreenTouch inside need2ChangeActivePointer() and the block that immediately follows the function call around line 110.

I'm not sure if changing the MouseMotions to ScreenTouches breaks anything but this worked for me.

**Comment by thrbr84** [comment]
Hi @rseonp , I'm sorry, I couldn't see the issue before.

I'm making some improvements, and these include a small adjustment to work by indexing the touch on the screen, so you can configure the analog to work only on the first finger touched on the screen, and so you can have other buttons for the second, third simultaneous touch.

I'll take a closer look at the change you suggested from MouseMotion to ScreenTouch.

Thanks for the support
